server:
  port: 8899

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sijanggaza;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create              # application 실행 시, 데이터 다 지우고 엔티티 정보를 통해 다시 생성
    properties:
      hibernate:
        #        show_sql: true             System.out.print를 통한 것
        format_sql: true
#        default_batch_fetch_size: 1000

logging:                            # log를 통한 것
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

decorator.datasource.p6spy.enable-logging: true

